openapi: 3.0.0
info:
  title: Auth Service API
  description: API de gestion d'authentification pour Snapshoot
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Serveur local via API Gateway
paths:
  /auth/register:
    post:
      summary: Inscription d'un nouvel utilisateur
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 6
                displayName:
                  type: string
      responses:
        '201':
          description: Utilisateur créé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                  token:
                    type: string
        '400':
          description: Données invalides
        '409':
          description: Email déjà utilisé
  /auth/login:
    post:
      summary: Connexion d'un utilisateur
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: Connexion réussie
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                  profile:
                    type: object
                    properties:
                      display_name:
                        type: string
                      username:
                        type: string
                      profile_image:
                        type: string
                  token:
                    type: string
        '401':
          description: Identifiants invalides
  # ... autres endpoints ...